In [1]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers
import networkx as nx
from rdkit import Chem

2025-08-22 10:27:18.971124: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-22 10:27:19.015168: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1755883639.027726   15332 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1755883639.032147   15332 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-08-22 10:27:19.082451: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
samplemol = "O=C(O)C1=C(COC(=N)O)CSC2N1C(=O)C2N=C(O)C(=NOC)C=3OC=CC3"
mol = Chem.MolFromSmiles(samplemol)

In [3]:
adj_matrix = Chem.GetAdjacencyMatrix(mol)
print(adj_matrix)

[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
import os
import pandas as pd

# where smiles->adj_matrix=data and spectrum=label

def load_data_array(folder):
    for file in os.listdir(folder):
        dataframe = pd.read_csv(os.path.join(folder, file))
        smiles = dataframe['SMILES']
        for smiles_str in smiles:
            mol = Chem.MolFromSmiles(smiles_str)
            dataframe['adj_matrix'] = Chem.GetAdjacencyMatrix(mol)
            adj_matrices = dataframe['adj_matrix']
    return np.array(adj_matrices)


In [19]:
folder = '../datasets/csv_conversions'

def smiles_to_adjacencymatrix(smiles_str):
    try:
        mol = Chem.MolFromSmiles(smiles_str)
        if mol is not None:
            return Chem.GetAdjacencyMatrix(mol)
        else:
            return None
    except:
        return None

for file in os.listdir(folder):
    dataframe = pd.read_csv(os.path.join(folder, file))
    smiles = dataframe['SMILES']
    dataframe['adj_matrix'] = dataframe['SMILES'].apply(smiles_to_adjacencymatrix)

dataframe

[23:07:59] SMILES Parse Error: Failed parsing SMILES 'CC1(C)[C@H](OC(C)=O)[C@H](O)C[C@]([C@@]1([H])CC[C@H]2C)(C)[C@]32CC4=C(O)C=C(CO)C(C=O)=C4O3&gt;&gt;' for input: 'CC1(C)[C@H](OC(C)=O)[C@H](O)C[C@]([C@@]1([H])CC[C@H]2C)(C)[C@]32CC4=C(O)C=C(CO)C(C=O)=C4O3&gt;&gt;'
[23:07:59] SMILES Parse Error: Failed parsing SMILES 'CC1(C)[C@H](OC(C)=O)CC[C@]([C@@]1([H])CC[C@H]2C)(C)[C@]32CC4=C(O)C=C(CO)C(C=O)=C4O3&gt;&gt;' for input: 'CC1(C)[C@H](OC(C)=O)CC[C@]([C@@]1([H])CC[C@H]2C)(C)[C@]32CC4=C(O)C=C(CO)C(C=O)=C4O3&gt;&gt;'
[23:07:59] SMILES Parse Error: Failed parsing SMILES 'CC1(C)[C@H](O)CC[C@]([C@@]1([H])CC[C@H]2C)(C)[C@]32CC4=C(O)C=C(C=O)C(C=O)=C4O3&gt;&gt;' for input: 'CC1(C)[C@H](O)CC[C@]([C@@]1([H])CC[C@H]2C)(C)[C@]32CC4=C(O)C=C(C=O)C(C=O)=C4O3&gt;&gt;'
[23:07:59] Explicit valence for atom # 1 N, 4, is greater than permitted
[23:07:59] Explicit valence for atom # 1 N, 4, is greater than permitted
[23:07:59] Explicit valence for atom # 9 Al, 6, is greater than permitted
[23:07:59] Explicit 

index                                             SMILES  \
0          0  O=C(O)C1OC(OC2C(O)C(O)C(OC2C)OC3CCC4(C)C(CCC5(...   
1          1  O=C(O)C1OC(OC2CCC3(C)C(CCC4(C)C3CCC56OCC7(CCC(...   
2          2  O=C(OC1OC(COC2OC(CO)C(OC3OC(C)C(O)C(O)C3O)C(O)...   
3          3  COC(C(=O)C(O)C(C)O)C1Cc2cc3cc(OC4CC(OC5CC(O)C(...   
4          4  O=C(OC1C(OC(OC2C(OC(OC3CC4=CCC5C(CCC6(C)C(CCC5...   
...      ...                                                ...   
33031  33031   O=C(O)CN=C(O)C(N=C(O)CCC(N)C(=O)O)CSSCC(N)C(=O)O   
33032  33032  O=S(=O)(O)OC1CC2=CCC3C(CCC4(C)C(CCC34)C(C)CCCC...   
33033  33033                             O=C(O)CN=C(O)CCCC(=O)O   
33034  33034                                    O=C(O)CC(=O)OCC   
33035  33035                             OC=1N=C(O)C(=C(N1)C)CO   

                                                Spectrum  \
0      {113.8722: 6.925926, 136.3651: 7.357357, 149.6...   
1                                     {1235.6047: 100.0}   
2      {73.02517: 3.410641, 161.04205: 8.867667, 197....   
3      {126.04706028498536: 0.00145236, 127.055915284...   
4      {85.028074: 25.84933, 87.007358: 10.664357, 87...   
...                                                  ...   
33031  {129.954: 11.355, 130.691: 11.074, 149.47: 10....   
33032  {465.48: 96.9263704402, 465.72: 100.0, 466.5: ...   
33033  {70.0: 4.306, 77.0: 5.841, 79.0: 3.523, 80.0: ...   
33034     {41.673: 100.0, 85.331: 23.365, 87.374: 100.0}   
33035   {96.087: 18.552, 138.992: 100.0, 156.943: 1.786}   

                                              adj_matrix  
0      [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
1      [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
2      [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
3      [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
4      [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
...                                                  ...  
33031  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
33032  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...  
33033  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, ...  
33034  [[0, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 1, 0, ...  
33035  [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, ...  

[33036 rows x 4 columns]

In [11]:
load_data_array('../datasets/csv_conversions')

ValueError: Length of values (88) does not match length of index (33036)

In [ ]:
class Sampling(layers.Layer):
    def call(self, input):
        mean, log_var = input
        batch = tf.shape(mean)[0]
        dim = tf.shape(mean)[1]
        epsilon = tf.random.normal(shape=(batch, dim))
        return mean + tf.exp(0.5*log_var) * epsilon

In [ ]:
# Encoder
latent_dim = 10
input_shape = (28,28,1)

encoder_inputs = keras.Input(shape=input_shape)

x = layers.Conv2D(64, 3, activation="relu", strides=2, padding="same")(encoder_inputs)
x = layers.Conv2D(128, 3, activation="relu", strides=2, padding="same")(x)
x = layers.Flatten()(x)
x = layers.Dense(16, activation="relu")(x)

mean = layers.Dense(latent_dim, name="mean")(x)
log_var = layers.Dense(latent_dim, name="log_var")(x)
z = Sampling()([mean, log_var])

encoder = keras.Model(encoder_inputs, [mean, log_var, z], name="encoder")
encoder.summary()

In [ ]:
# Decoder
latent_inputs = keras.Input(shape=(latent_dim,))

x = layers.Dense(7 * 7 * 64, activation="relu")(latent_inputs)
x = layers.Reshape((7, 7, 64))(x)
x = layers.Conv2DTranspose(128, 3, activation="relu", strides=2, padding="same")(x)
x = layers.Conv2DTranspose(64, 3, activation="relu", strides=2, padding="same")(x)

decoder_outputs = layers.Conv2DTranspose(1, 3, activation="sigmoid", padding="same")(x)
decoder = keras.Model(latent_inputs, decoder_outputs, name="decoder")
decoder.summary()

In [ ]:
class VariationalAutoencoder(keras.Model):
    def __init__(self, encoder, decoder, **kwargs):
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.total_loss_tracker = keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = keras.metrics.Mean(name="reconstruction_loss")
        self.kl_loss_tracker = keras.metrics.Mean(name="kl_loss")

    @property
    def metrics(self):
        return [self.total_loss_tracker, self.reconstruction_loss_tracker, self.kl_loss_tracker]
    
    def train(self, data):
        with tf.GradientTape as gt:
            mean, log_var, z = self.encoder(data)
            reconstruct = self.decoder(z)
            reconst_loss = tf.reduce_mean(
                tf.reduce_mean(
                    keras.losses.binary_crossentropy(data, reconstruct),
                    axis=(1, 2)
                ) 
            )
            kl_loss = -0.5 * (1 + log_var - tf.square(mean) - tf.exp(log_var))
            kl_loss = tf.reduce_mean(tf.reduce_sum(kl_loss, axis=1))
            total_loss = reconst_loss + kl_loss
        grads = gt.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconst_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            "loss": self.total_loss_tracker.result(),
            "reconst_loss": self.reconstruction_loss_tracker.result(),
            "kl_loss": self.kl_loss_tracker.result()
        }

In [ ]:
import matplotlib.pyplot as plt

def plot_latent_space(vae, n=10, figsize=5):
    
    img_size = 28
    scale = 0.5
    figure = np.zeros((img_size * n, img_size * n))
    
    grid_x = np.linspace(-scale, scale, n)
    grid_y = np.linspace(-scale, scale, n)[::-1]

    for i, yi in enumerate(grid_y):
        for j, xi in enumerate(grid_x):
            sample = np.array([[xi, yi]])
            x_decoded = vae.decoder.predict(sample, verbose=0)
            images = x_decoded[0].reshape(img_size, img_size)
            figure[
                i * img_size : (i + 1) * img_size,
                j * img_size : (j + 1) * img_size,
            ] = images

    plt.figure(figsize=(figsize, figsize))
    start_range = img_size // 2
    end_range = n * img_size + start_range
    pixel_range = np.arange(start_range, end_range, img_size)
    sample_range_x = np.round(grid_x, 1)
    sample_range_y = np.round(grid_y, 1)
    plt.xticks(pixel_range, sample_range_x)
    plt.yticks(pixel_range, sample_range_y)
    plt.xlabel("z[0]")
    plt.ylabel("z[1]")
    plt.imshow(figure, cmap="Greys_r")
    plt.show()

In [ ]:
def plot_label_clusters(encoder, decoder, data, test_lab, labels):
	z_mean, _, _ = encoder.predict(data)
	plt.figure(figsize =(12, 10))
	sc = plt.scatter(z_mean[:, 0], z_mean[:, 1], c = test_lab)
	cbar = plt.colorbar(sc, ticks = range(10))
	cbar.ax.set_yticklabels([labels.get(i) for i in range(10)])
	plt.xlabel("z[0]")
	plt.ylabel("z[1]")
	plt.show()